# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Camera2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
import os

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 680)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1400, 680))
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

        self.title = QtWidgets.QLabel(self.frame)
        self.title.setGeometry(QtCore.QRect(0, 0, 1200, 60))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")

        self.title1 = QtWidgets.QLabel(self.frame)
        self.title1.setGeometry(QtCore.QRect(230, 110, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(75)
        self.title1.setFont(font)
        self.title1.setAlignment(QtCore.Qt.AlignCenter)
        self.title1.setObjectName("title1")

        self.title2 = QtWidgets.QLabel(self.frame)
        self.title2.setGeometry(QtCore.QRect(725, 110, 130, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(75)
        self.title2.setFont(font)
        self.title2.setAlignment(QtCore.Qt.AlignCenter)
        self.title2.setObjectName("title2")

        self.video1 = QtWidgets.QLabel(self.frame)
        self.video1.setGeometry(QtCore.QRect(50, 140, 420, 420))
        self.video1.setAutoFillBackground(True)
        self.video1.setAlignment(QtCore.Qt.AlignCenter)
        self.video1.setStyleSheet("QLabel{background:#000000;}"
                                  "QLabel{color:rgb(300,300,300,120);font-size:10px;font-weight:bold;font-family:宋体;}")
        self.video1.setObjectName("video1")

        self.video2 = QtWidgets.QLabel(self.frame)
        self.video2.setGeometry(QtCore.QRect(580, 140, 420, 420))
        self.video2.setAutoFillBackground(True)
        self.video2.setAlignment(QtCore.Qt.AlignCenter)
        self.video2.setStyleSheet("QLabel{background:#000000;}"
                                  "QLabel{color:rgb(300,300,300,120);font-size:10px;font-weight:bold;font-family:宋体;}")
        self.video2.setObjectName("video2")


        '''==================detect======================================'''

        self.detect = QtWidgets.QLabel(self.frame)
        self.detect.setGeometry(QtCore.QRect(1230, 140, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(65)
        self.detect.setFont(font)
        self.detect.setAlignment(QtCore.Qt.AlignCenter)
        self.detect.setObjectName("detect")
        
        self.buttonGroup1 = QtWidgets.QButtonGroup(self.frame)

        self.yolov3 = QtWidgets.QRadioButton(self.frame)
        self.yolov3.setGeometry(QtCore.QRect(1250, 190, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.yolov3.setFont(font)
        self.yolov3.setChecked(False)
        self.yolov3.setObjectName("yolov3")
        self.buttonGroup1.addButton(self.yolov3)
        
        self.yolov5 = QtWidgets.QRadioButton(self.frame)
        self.yolov5.setGeometry(QtCore.QRect(1250, 230, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.yolov5.setFont(font)
        self.yolov5.setChecked(False)
        self.yolov5.setObjectName("yolov5")
        self.buttonGroup1.addButton(self.yolov5)

        '''=======================pose====================================='''
        
        self.pose = QtWidgets.QLabel(self.frame)
        self.pose.setGeometry(QtCore.QRect(1230, 290, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(65)
        self.pose.setFont(font)
        self.pose.setAlignment(QtCore.Qt.AlignCenter)
        self.pose.setObjectName("pose")
        
        self.buttonGroup2 = QtWidgets.QButtonGroup(self.frame)

        self.alphapose = QtWidgets.QRadioButton(self.frame)
        self.alphapose.setGeometry(QtCore.QRect(1250, 340, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.alphapose.setFont(font)
        self.alphapose.setChecked(False)
        self.alphapose.setObjectName("alphapose")
        self.buttonGroup2.addButton(self.alphapose)

        '''====================stgcn======================================'''
        
        self.action = QtWidgets.QLabel(self.frame)
        self.action.setGeometry(QtCore.QRect(1230, 440, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(65)
        self.action.setFont(font)
        self.action.setAlignment(QtCore.Qt.AlignCenter)
        self.action.setObjectName("action")
        
        self.buttonGroup3 = QtWidgets.QButtonGroup(self.frame)

        self.stgcn = QtWidgets.QRadioButton(self.frame)
        self.stgcn.setGeometry(QtCore.QRect(1250, 490, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.stgcn.setFont(font)
        self.stgcn.setChecked(False)
        self.stgcn.setObjectName("stgcn")
        self.buttonGroup3.addButton(self.stgcn)

        '''===================模式选择========================================='''
        self.buttonGroup = QtWidgets.QButtonGroup(self.frame)

        self.model_select = QtWidgets.QLabel(self.frame)
        self.model_select.setGeometry(QtCore.QRect(1070, 140, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.model_select.setFont(font)
        self.model_select.setAlignment(QtCore.Qt.AlignCenter)
        self.model_select.setObjectName("model_select")

        self.rb_fall = QtWidgets.QRadioButton(self.frame)
        self.rb_fall.setGeometry(QtCore.QRect(1070, 200, 89, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.rb_fall.setFont(font)
        self.rb_fall.setChecked(True)
        self.rb_fall.setObjectName("rb_fall")
        self.buttonGroup.addButton(self.rb_fall)

        self.rb_danao = QtWidgets.QRadioButton(self.frame)
        self.rb_danao.setGeometry(QtCore.QRect(1070, 240, 89, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.rb_danao.setFont(font)
        self.rb_danao.setObjectName("rb_danao")
        self.buttonGroup.addButton(self.rb_danao)

        self.rb_jump = QtWidgets.QRadioButton(self.frame)
        self.rb_jump.setGeometry(QtCore.QRect(1070, 280, 89, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.rb_jump.setFont(font)
        self.rb_jump.setObjectName("rb_jump")
        self.buttonGroup.addButton(self.rb_jump)

        self.rb_other = QtWidgets.QRadioButton(self.frame)
        self.rb_other.setGeometry(QtCore.QRect(1070, 320, 89, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.rb_other.setFont(font)
        self.rb_other.setObjectName("rb_other")
        self.buttonGroup.addButton(self.rb_other)
        
        '''================================================================'''
        
        self.bn_openfile = QtWidgets.QPushButton(self.frame)
        self.bn_openfile.setGeometry(QtCore.QRect(50, 610, 90, 25))
        self.bn_openfile.setObjectName("bn_openfile")

        self.bn_pause = QtWidgets.QPushButton(self.frame)
        self.bn_pause.setGeometry(QtCore.QRect(160, 610, 90, 25))
        self.bn_pause.setObjectName("bn_pause")

        self.bn_opencam1 = QtWidgets.QPushButton(self.frame)
        self.bn_opencam1.setGeometry(QtCore.QRect(270, 610, 100, 25))
        self.bn_opencam1.setObjectName("bn_opencam1")

        self.bn_opencam2 = QtWidgets.QPushButton(self.frame)
        self.bn_opencam2.setGeometry(QtCore.QRect(390, 610, 100, 25))
        self.bn_opencam2.setObjectName("bn_opencam2")

        self.bn_end = QtWidgets.QPushButton(self.frame)
        self.bn_end.setGeometry(QtCore.QRect(510, 610, 90, 25))
        self.bn_end.setObjectName("bn_end")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1568, 23))
        self.menubar.setObjectName("menubar")

        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "人体异常行为检测系统-V1.0"))
        self.setWindowIcon(QIcon(os.getcwd() + '\\data_img\\source_image\\yolov3ive.ico'))
        self.title.setText(_translate("MainWindow", "人体异常行为检测系统-V1.0"))
        self.title1.setText(_translate("MainWindow", "原视频"))
        self.title2.setText(_translate("MainWindow", "处理后视频"))
        self.video1.setText(_translate("MainWindow", "原视频"))
        self.video2.setText(_translate("MainWindow", "检测结果"))

        self.model_select.setText(_translate("MainWindow", "模式选择"))
        self.rb_fall.setText(_translate("MainWindow", "跌倒"))
        self.rb_danao.setText(_translate("MainWindow", "打闹"))
        self.rb_jump.setText(_translate("MainWindow", "蹦跳"))
        self.rb_other.setText(_translate("MainWindow", "..."))

        self.bn_openfile.setText(_translate("MainWindow", "打开视频文件"))
        self.bn_pause.setText(_translate("MainWindow", "暂停"))
        self.bn_opencam1.setText(_translate("MainWindow", "打开本地摄像头"))
        self.bn_opencam2.setText(_translate("MainWindow", "打开网络摄像头"))
        self.bn_end.setText(_translate("MainWindow", "结束"))

        self.detect.setText(_translate("MainWindow", "目标检测"))
        self.yolov3.setText(_translate("MainWindow", "yolov3"))
        self.yolov5.setText(_translate("MainWindow", "yolov5"))

        self.pose.setText(_translate("MainWindow", "姿态估计"))
        self.alphapose.setText(_translate("MainWindow", "alphapose"))

        self.action.setText(_translate("MainWindow", "动作识别"))
        self.stgcn.setText(_translate("MainWindow", "st-gcn"))



